[package]
name = "convert"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
ron = "*"
bincode = "1.3.3"
quizlib = {path= "../../quizlib/"}
